### ISSUE TITLE
Don't work Speed Control. Always Full Speed.

### ISSUE THREAD

**Issue by ShiN-K-278** [takamin/mz700-js#137]
Don't work Speed Control. Always Full Speed.

**Comment by takamin** [comment]
Indeed, sorry, I had commited the experimental changes to the master branch.

Is the speed too fast on your environment?

I was planning to remove the feature.

If the speed is fast enough, I think that the feature should be remained to slow down.

**Comment by ShiN-K-278** [comment]
Yes, it's too fast. It is about three to ten times faster. My environment is Chrome on macOS 10.14. Reverting to MZ700-JS 1.1.3 with backup did not solve the speed problem.

**Comment by takamin** [comment]
Hi @ShiN-K-278, Thank you for your valuable information.
I fixed the slider issue and pushed a branch named `control-clock`.
On the branch, you can change the speed by the slider.

I will merge the branch to `master` after some test and confirmation.

**Comment by takamin** [comment]
I had confirmed the speed is about two times faster on the latest Firefox for Windows.
And currently MS-Edge could not run this emulator by some error.

**Comment by ShiN-K-278** [comment]
Speed ​​adjustment was possible with v1.2.0. Thank you very much. Around 33% is just right speed.
