### ISSUE TITLE
v1.2.4 or later cannot be installed.

### ISSUE THREAD

**Issue by ShiN-K-278** [takamin/mz700-js#157]
v1.2.4 or later cannot be installed. Below is the log.

...
Running "browserify:build" (browserify) task
>> Error: Cannot find module 'js-cookie' from '/Users/hogehoge/.nvm/versions/node/v12.13.0/lib/node_modules/mz700-js/lib'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! mz700-js@1.2.9 postinstall: `grunt release`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the mz700-js@1.2.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hogehoge/.npm/_logs/2019-11-15T12_53_09_792Z-debug.log

**Comment by takamin** [comment]
Thanks your report. I confirmed the installation fail.
The npm js-cookie was installed as a module for development environment, but it should be instaled as runtime module.
Please wait till I fix this problem. I will do that soon.

**Comment by takamin** [comment]
Hi @ShiN-K-278 I published the mz700-js@1.2.10 that fixes the problem in global installation.
Please try to install the version, and close this issue if you done.

**Comment by ShiN-K-278** [comment]
It was confirmed that installation and operation are possible. Thank you very much.
