### ISSUE TITLE
Displacement d is unsigned (should be signed) in (IX+d) and (IY+d)

### ISSUE THREAD

**Issue by helderman** [takamin/mz700-js#161]
In instructions like `LD A,(IX+d)`, the emulator considers the 8-bit displacement `d` as an unsigned integer, ranging from 0 up to and including 255.

This is incorrect. A real Z80 considers `d` as a signed integer, ranging from -128 up to and including +127. It is typically sign-extended to 16 bits before being added to `IX` or `IY`. This is similar to the way `e` is added to the program counter in relative jumps like `JR e`.

For example, `DD 7E FF` is the object code for `LD A,(IX-1)`. The emulator incorrectly interprets it as `LD A,(IX+255)`.

This is a serious dealbreaker for programs that rely on indexed addressing.

The issue is easy to reproduce with the following program. It should print digits 123456789 at the top left of the screen. In the emulator, digit 9 is printed on the right spot, all others are printed in the center of the screen.

```
0000   DD 21 59 D0            LD   IX,0D059h   
0004   DD 36 00 29            LD   (IX+0),29h   
0008   DD 36 FF 28            LD   (IX-1),28h   
000C   DD 36 FE 27            LD   (IX-2),27h   
0010   DD 36 FD 26            LD   (IX-3),26h   
0014   DD 36 FC 25            LD   (IX-4),25h   
0018   DD 36 FB 24            LD   (IX-5),24h   
001C   DD 36 FA 23            LD   (IX-6),23h   
0020   DD 36 F9 22            LD   (IX-7),22h   
0024   DD 36 F8 21            LD   (IX-8),21h   
0028   76                     HALT
```

**Comment by takamin** [comment]
Hi @helderman,  thanks to open this issue.
What a epic misunderstanding! I have ever believed that the `d` is unsigned.
I think it may fix some potential bugs.

**Comment by helderman** [comment]
Thank you for the rapid fix! Happy to confirm the issue has been resolved.
