### ISSUE TITLE
Incorrect calculation in 8-bit ADC instruction

### ISSUE THREAD

**Issue by helderman** [takamin/mz700-js#164]
`ADC A,s` and `ADC A,n` always return either 0 or 1 (value depends on the intended result being even or odd). Effectively, the instruction clears all bits except bit 0 when storing the result of the addition in the accumulator.

Appears to be a parenthesis bug in register.ts, line 384:

`const q = (this.getA() + n + (this.getF()) & Z80_Register.C_FLAG);`

Should be:

`const q = this.getA() + n + (this.getF() & Z80_Register.C_FLAG);`

**Comment by takamin** [comment]
@helderman Thanks your cheking and reporting.
Indeed, the code seems apparently weird.
I would confirm.

**Comment by helderman** [comment]
Thank you for the fast response! I can confirm that the issue has been resolved. The following MZT file should show a maze; the bug would cause the vertical lines to be suppressed, showing only the horizontal lines.
https://helderman.github.io/infinite-hash-maze/z80/mazeview.mzt

**Comment by takamin** [comment]
I just confirmed it. The latest draws this. Is a correct?
![image](https://user-images.githubusercontent.com/952896/70901016-4e7b0380-203d-11ea-9016-f7835054327e.png)

v1.2.13 drew only horizontal lines:
![image](https://user-images.githubusercontent.com/952896/70900882-0f4cb280-203d-11ea-9eef-d2c6156ef48d.png)

**Comment by helderman** [comment]
Correct, I witnessed the same behavior. Thanks again for the bugfix!
