### ISSUE TITLE
Very small program makes emulator halt

### ISSUE THREAD

**Issue by helderman** [takamin/mz700-js#166]
While testing another issue (#161), I noticed something weird. When trying to load a very small program, the emulated CPU will stop at whatever instruction it was busy with before loading the new program. This could be an instruction in the monitor's keyboard handler, but it could also be an instruction of the currently running program that had been loaded before loading the new program. So it would appear the problem does not occur while executing the new program, but earlier, possibly while loading the new program into memory.

This seems to happen only with programs of 11 instructions or less. Programs with 12 instructions or more are fine. The number of bytes does not appear to matter; it's really about the number of _instructions_.

Workaround: pad your program with NOP instructions.

Steps to reproduce:

1. Make an MZT file from the assembly program below.
2. Drag and drop the MZT file onto the emulator.
3. Notice that digits appear on screen - OK.
4. Remove the NOP instructions. Make a new MZT file.
5. Restart the emulator. Drag and drop the MZT file onto the emulator.
6. Notice the 'cmt' name is not updated - not OK.
7. Notice the emulator freezes on some instruction in the monitor - not OK.

```
0000   DD 21 4A D1            LD   IX,0D000H+330   
0004   DD 36 7E 29            LD   (IX+126),29h   
0008   DD 36 7F 28            LD   (IX+127),28h   
000C   DD 36 80 27            LD   (IX-128),27h   
0010   DD 36 81 26            LD   (IX-127),26h   
0014   DD 36 82 25            LD   (IX-126),25h   
0018   76                     HALT   
0019   00                     NOP   
001A   00                     NOP   
001B   00                     NOP   
001C   00                     NOP   
001D   00                     NOP   
```

**Comment by takamin** [comment]
I confirmed the problem was reproduced and found that occured at least in the function `disassemble`  that is declared at 201 line of `MZ-700/mz700-emu.js`.

I would continue to debug.

The program that I loaded:

```
ORG     1200H
LD      IX,0D14AH
LD      (IX+126),29h
LD      (IX+127),28h
LD      (IX-128),27h
LD      (IX-127),26h
LD      (IX-126),25h
HALT
```

**Comment by takamin** [comment]
It was very simply bug I made. The condition for the top-index of line to display in the assembled list was not correct.
